version: '2'
services:
  api:
      image: ponto-track-back
      build: .
      ports:
        - "7015:7015"
      restart: on-failure
      container_name: ponto-track-back
      command: npm run dev
      volumes:
        - .:/app
        - /app/node_modules
      env_file:
        - .env

