version: '2'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ponto-track-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ponto-track-db
    ports:
      - "4005:3306"
    volumes:
      - new-mysql-data:/var/lib/mysql
  api:
    image: ponto-track-back
    build: .
    ports:
      - "7015:7015"
    restart: on-failure
    container_name: ponto-track-back
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

volumes:
  new-mysql-data:
    driver: local
