version: '2'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ponto-track-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ponto-track-db
    ports:
      - "4005:4005"
    volumes:
      - mysql-data:/var/lib/mysql
